name: PR
on:
  pull_request_target:
    branches: master

concurrency:
  group: PR-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  labeler:
    name: 'Pull Request Labeler'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Generate dynamic labels
        run: |
          chmod +x ./tools/ci/list-directories.sh
          ./tools/ci/list-directories.sh >> .github/labeler.yml
      - name: Print .github/labeler.yml contents
        run: cat .github/labeler.yml
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
